### ISSUE TITLE
Problema al buildear

### ISSUE THREAD

**Issue by iglosiggio** [HuayraLinux/huayra-curriculum#1]
1. Obviamente por como funca linux faltaría aclarar cuáles son los paquetes que hay que tener instalados globalmente (o en el path al menos), en mi caso creo que bower nada más, tuve que hacer un "sudo npm install -g bower"

2. Una vez hecho el "make actualizar" esperé que funcionara el make test_linux. Tuve estos errores ¿Es posible que falte alguna dependencia?

```
alumno@mega /t/huayra-curriculum> make test_linux 
./node_modules/ember-cli/bin/ember build
version: 0.1.4
Could not find watchman, falling back to NodeWatcher for file system events
Building..
adapters/application.js: line 10, col 34, 'url' is defined but never used.
adapters/application.js: line 33, col 48, 'newDoc' is defined but never used.
adapters/application.js: line 51, col 79, 'newDoc' is defined but never used.
adapters/application.js: line 51, col 66, 'numReplaced' is defined but never used.
adapters/application.js: line 68, col 61, 'numRemoved' is defined but never used.
adapters/application.js: line 83, col 9, 'result' is defined but never used.
adapters/application.js: line 81, col 35, 'record' is defined but never used.

7 errors

components/huayra-pasos.js: line 21, col 42, Expected '===' and instead saw '=='.
components/huayra-pasos.js: line 22, col 7, Missing semicolon.

2 errors

controllers/asistente/paso6.js: line 35, col 15, 'fs' is not defined.
controllers/asistente/paso6.js: line 10, col 27, 'evt' is defined but never used.
controllers/asistente/paso6.js: line 29, col 24, 'd' is defined but never used.

3 errors

===== 3 JSHint Errors

Build failed.
Path or pattern "vendor/ember-components/vendor/ic-styled/main.js" did not match any files
Error: Path or pattern "vendor/ember-components/vendor/ic-styled/main.js" did not match any files
    at Object.multiGlob (/tmp/huayra-curriculum/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at /tmp/huayra-curriculum/node_modules/ember-cli/node_modules/broccoli-concat/index.js:62:32
    at $$$internal$$tryCatch (/tmp/huayra-curriculum/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
    at $$$internal$$invokeCallback (/tmp/huayra-curriculum/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:482:17)
    at $$$internal$$publish (/tmp/huayra-curriculum/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:453:11)
    at $$rsvp$asap$$flush (/tmp/huayra-curriculum/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1531:9)
    at process._tickCallback (node.js:419:13)
Makefile:27: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by iglosiggio** [comment]
https://github.com/indexiatech/ember-components/issues/42
Parece tener que ver con esta issue

**Comment by hugoruscitti** [comment]
Si, efectivamente se soluciona con la propuesta de @jackmatt2:

https://github.com/indexiatech/ember-components/issues/42#issuecomment-66395512

On Tue, Jan 6, 2015 at 10:07 PM, Ignacio Losiggio <notifications@github.com>
wrote:

> indexiatech/ember-components#42
> <https://github.com/indexiatech/ember-components/issues/42>
> Parece tener que ver con esta issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HuayraLinux/huayra-curriculum/issues/1#issuecomment-68963469>
> .
>



-- 
Hugo Ruscitti

www.pilas-engine.com.ar
www.examplelab.com.ar
www.losersjuegos.com.ar

**Comment by hugoruscitti** [comment]
Debería quedar resuelto con la migración a ember 2.6 del issue #3 , y la última actualización del paquete a la versión 0.2.1 https://github.com/HuayraLinux/huayra-curriculum/commit/249be3baf423bf7f481066cc8ff82fa5be66faea

¿Me confirmás @iglosiggio si en tu equipo también compila correctamente?, así damos por cerrado este issue :) 

PD: para mí lo siguiente a realizar es pasar la app a electron o agregar el arreglo de wm_class, lo que vos prefieras.

**Comment by iglosiggio** [comment]
Daleee! 👍
